namespace InterviewCleanApi.Domain.Common;

public abstract class BaseEntity
{
    /// <summary>
    ///     Primary key generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    ///     UTC timestamp set when the entity is created.
    /// </summary>
    public DateTime CreatedAtUtc { get; set; }
}