using InterviewCleanApi.Domain.Common;
using InterviewCleanApi.Domain.Enums;

namespace InterviewCleanApi.Domain.Entities;

/// <summary>
///     Represents an authenticated application user.
/// </summary>
public sealed class AppUser : BaseEntity
{
    /// <summary>
    ///     Display name used by the application.
    /// </summary>
    public required string UserName { get; set; }

    /// <summary>
    ///     Unique email used as the login identifier.
    /// </summary>
    public required string Email { get; set; }

    /// <summary>
    ///     Password hash generated by the configured password hasher.
    /// </summary>
    public required string PasswordHash { get; set; }

    /// <summary>
    ///     Authorization role embedded into JWT claims.
    /// </summary>
    public UserRole Role { get; set; } = UserRole.User;
}