@InterviewCleanApi_HostAddress = http://localhost:5000
@token = your_jwt_token_here

### Registrar usuario
POST {{InterviewCleanApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "userName": "john",
  "email": "john@test.com",
  "password": "123456"
}

### Login
POST {{InterviewCleanApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "123456"
}

### Obtener productos
GET {{InterviewCleanApi_HostAddress}}/api/products
Accept: application/json
Authorization: Bearer {{token}}

### Crear producto
POST {{InterviewCleanApi_HostAddress}}/api/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Laptop 2",
  "description": "Laptop para pruebas 2",
  "price": 850.50,
  "stock": 5
}

### Obtener producto por id
GET {{InterviewCleanApi_HostAddress}}/api/products/1
Accept: application/json
Authorization: Bearer {{token}}

### Actualizar producto
PUT {{InterviewCleanApi_HostAddress}}/api/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Laptop Pro",
  "description": "Actualizada",
  "price": 999.99,
  "stock": 10
}

### Eliminar producto
DELETE {{InterviewCleanApi_HostAddress}}/api/products/1
Authorization: Bearer {{token}}